version: "3.7"

services:
  kontext:
    environment:
      - STATUS_SERVICE_URL=${STATUS_SERVICE_URL}

  ws:
    image: czcorpus/kontext-ws
    volumes:
      - ${KONTEXT_CONFIG}:/opt/kontext/conf/config.xml
      - corpora-data:/var/lib/manatee
      - corpora-cache:/var/local/copora
    networks:
      - databases
      - kontext
    depends_on: 
      - redis
      - kontext

  nginx:
    volumes:
      - ./conf/nginx.ws.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ws

volumes:
  corpora-data: {}
  corpora-cache: {}

networks:
  databases: {}
  kontext: {}