version: '3.7'

services:
  mariadb:
    image: czcorpus/kontext-mariadb
    environment:
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mdbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - databases

volumes:
  mdbdata: {}

networks:
  databases: {}