version: '3.7'

services:
  kontext:
    networks:
      - mariadb
    depends_on:
      - mariadb

  rq-worker:
    networks:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    image: czcorpus/kontext-mariadb
    environment:
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mdbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mariadb

volumes:
  mdbdata: {}

networks:
  mariadb: {}